name: Build and test

on:
  push:
    branches: ["main"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          cacheFrom: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          push: always

  build-cpp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    needs: build-image
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    # Repeated steps (checkout+login-action) should be their own action
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7.0.1
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3.1900000349
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        with:
          imageName: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          cacheFrom: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          push: never
          runCmd: |
            cmake --preset=toolchain-vcpkg
            cmake --build --preset=SearchMersennePrime

  test-cpp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    needs: [build-image, build-cpp]
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7.0.1
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          cacheFrom: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          push: never
          runCmd: |
            cmake --preset=toolchain-vcpkg
            cmake --build --preset=LibMersennePrimer_test
            cd out/build/toolchain-vcpkg && ctest --output-on-failure
