name: Build C++ in Devcontainer

on:
  push:
    branches: ["main"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          cacheFrom: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          push: always

  build-cpp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    needs: build-image

    # Repeated steps (checkout+login-action) should be their own action
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          cacheFrom: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          push: never
          runCmd: |
            cmake --preset=toolchain-vcpkg
            cmake --build --preset=SearchMersennePrime

  test-cpp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    needs: [build-image, build-cpp]

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          cacheFrom: ghcr.io/vppiet/search-mersenne-prime-devcontainer
          push: never
          runCmd: |
            cmake --preset=toolchain-vcpkg
            cmake --build --preset=LibMersennePrimer_test
            cd out/build/toolchain-vcpkg && ctest --output-on-failure
